import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const fontSans = Sora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.className, 'antialiased')}>{children}</body>
    </html>
  )
}
